#!/bin/csh
#SBATCH -N 256
#SBATCH -t 00:07:00
#SBATCH -p pbatch

# Run info and srun job launch
srun -n 256 /p/lscratchh/hamon1/GEOSX/build-quartz-gcc@8.1.0-release/bin/geosx --input hi24l_singlephase_bc_large_heterogeneous.xml
echo 'Done'
